artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: url= "https://drive.google.com/file/d/13ajoufJy_-6ImznjsgDYFmxqZzKnqQCB/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
